<a href="https://colab.research.google.com/github/Nithya1111/Python_Data_Science_Course/blob/master/Numpy_Assignment_Day_10_Nithya.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center> Numpy Basics </center>

In [30]:
#import numpy module with alias np
import numpy as np


We can create a NumPy ndarray object by using the array() function.
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:


In [31]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it
arr = np.array([1,2,3])


In [32]:
# print output

arr

array([1, 2, 3])

## Dimensions in Arrays

Create arrays of different dimentions.

a=A numpy array with one single integer 10

b=A numpy array passing a list having a list= [1,2,3]

c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements

d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements

In [33]:
#define a,b,c and d as instructed above

#a = np.array(10)
#b = np.array([1,2,3])
#c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])



Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [34]:
#print dimentions of a,b, c and d

#a.ndim
#b.ndim
#c.ndim
d.ndim


3

Hey hey. Did you see! you have created 0-D,1-DeprecationWarning, 2-D and 3-D arrays.

Lets print there shape as well. You can check shape using shape attribute



In [35]:
# print shape of each a,b ,c and d

a.shape
b.shape
c.shape
d.shape


NameError: ignored

Lets check data type passed in our array. To check data type you can use dtype attribute

In [ ]:
# print data type of c and d
#c.dtype
d.dtype



Above output mean our array is having int type elements in it.

Lets check the type of our variable. To check type of any numpy variable use type() function

In [ ]:
#print type of a and b variable
type(a)
type(b)





In [ ]:
# Lets check length of array b, using len() function
len(b)

Bravo!You have Defined ndarray i.e numpy array in variable a nd b. Also you have successfully learned how to create numpy.

Create two list l1 and l2 where, l1=[10,20,30] and l2=[40,50,60]
Also define two numpy arrays l3,l4 where l3 has l1 as element and l4 has l2 as element


In [ ]:
# Define l1,l2,l3 and l4 as stated above.
l1 = [10,20,30]
l2 = [40,50,60]
l3 = np.array(l1)
l4 = np.array(l2)



Lets multiply each elements of l1 with corresponding elements of l2

Here use list comprehention to do so. Lets see how much you remember your work in other assignments.

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line<br>
eg. %timeit my_code

In [ ]:
#code here as instructed above

%timeit result = [x * y for x, y in zip(l1, l2)]


Lets mulptiply l3 and l4

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line

In [ ]:

%timeit my_code = np.multiply(l3,l4)


Don't worry if still your one line of code is running. Its because your system is calculating total time taken to run your code.

Did you notice buddy! time taken to multiply two lists takes more time than multiplyimg two numpy array.
Hence proved that numpy arrays are faster than lists.

**Fun Fact time!:**

You know in many data science interviews it is asked that what is the difference between list and array.<br>


In [ ]:
#Create a numpy array using arange with 1 and 11 as parameter in it

my_arr = np.arange(1,11)
my_arr

This means using arrange we get evenly spaced values within a given interval. Interval? Yes you can mention interval as well as third parameter in it.

In [ ]:
# Create an array using arange passing 1,11 and 2 as parameter in iter

my_arr2 = np.arange(1,11,2)
my_arr2

In [ ]:
# create numpy array using eye function with 3 as passed parameter

my_arr3 = np.eye(3)
my_arr3

In [ ]:
# Using arange() to generate numpy array x with numbers between 1 to 16
x= np.arange(1,17)
x



In [ ]:
# Reshape x with 2 rows and 8 columns
new_x = x.reshape(2,8)
new_x

As you can see above that our x changed into 2D matrix

2. Reshaping 1-D to 3-D array


In [ ]:
# reshaoe x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:
new_x1 = x.reshape(2,4,2)
new_x1


In [ ]:
# Use unknown dimention to reshape x into 2-D numpy array with shape 4*4

new_x2 = x.reshape(4, -1)

new_x2

In [ ]:
# Use unknown dimention to  reshape x into 3-D numpy array with 2 arrays that contains 4 arrays
y=new_x2.reshape(2,4,-1)
print(y)



In [ ]:
# Flattening y
flattened_y = y.flatten()

flattened_y

In [ ]:
# Create an array a with all even numbers between 1 to 17
a = np.arange(2,18,2)


print(a)


In [ ]:
# Get third element in array a
print(a[2])

In [ ]:
#Print 3rd, 5th, and 7th element in array a
print(a[2])
print(a[4])
print(a[6])

Lets check the same for 2 D array

In [ ]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
a = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [ ]:
# print the 3rd element from the 3rd row of a

print(a[2,2])

Well done!

Now lets check indexing for 3 D array

In [ ]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
b


In [ ]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.

third_element = a[1,2]
third_element


In [ ]:
# Create 1D array

arr= np.array([1,3,5,7,9,11])




In [ ]:
# Slice elements from 1st to 5th element from the following array:

print(arr[0:5])



Note: The result includes the start index, but excludes the end index.



In [ ]:
# Slice elements from index 5 to the end of the array:

print(arr[5:])


In [ ]:
# Slice elements from the beginning to index 5 (not included):

print(arr[:4])



**STEP**

Use the step value to determine the step of the slicing:

In [ ]:
# Print every other element from index 1 to index 7:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[1:8:2])
every_other_element = arr[::2]
print(arr)


Did you see? using step you were able to get alternate elements within specified index numbers.

In [ ]:
# Return every other element from the entire array arr:
print(every_other_element)



well done!

Lets do some slicing on 2-D array also. We already have 'a' as our 2-D array. We will use it here.

**Array slicing in 2-D array.**

In [ ]:
# Print array a

a

In [ ]:
# From the third element, slice elements from index 1 to index 5 (not included) from array 'a'

sliced_element = a[2, 1:5]
sliced_element


In [ ]:
# In array 'a' print index 2 from all the elements :

index_2 = a[:, 2]
index_2


In [ ]:
# From all the elements in 'a', slice index 1 till end, this will return a 2-D array:

index_1 = a[:,1:]
index_1

Hurray! You have learned Slicing in Numpy array. Now you know to access any numpy array.

## Numpy copy vs view

In [38]:
x1=np.copy(a)



In [43]:
# assign x2 = x1

x2=x1.copy()

In [44]:
#print x1 and x2

#x1
x2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Ok now you have seen that both of them are same

In [45]:
# change 1st element of x2 as 10
x2[0] =10



In [48]:
#Again print x1 and x2
#x1
x2


array([[10, 10, 10],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
# Check memory share between x1 and x2

memory_sharex1 = np.shares_memory(x1,x2)
memory_sharex1

Hey It's True they both share memory

Shall we try **view()** function also likwise.

In [ ]:
# Create a view of x1 and store it in x3.
x3 = x1.view()


In [ ]:
# Again check memory share between x1 and x3
memory_sharex3 = np.shares_memory(x1,x3)
memory_sharex3


Woh! simple assignment is similar to view. That means
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

Don't agree? ok lets change x3 and see if original array i.e. x1 also changes

In [ ]:
#Change 1st element of x3=100
x3[0] = 100


In [ ]:
#print x1 and x3 to check if changes reflected in both

#x1
x3

Now its proved.

Lets see how **Copy()** function works

In [39]:
# Now create an array x4 which is copy of x1

x4=np.copy(x1)



In [40]:
# Change the last element of x4 as 900
x4[2] = 900




In [41]:
# print both x1 and x4 to check if changes reflected in both

#x1
x4


array([[  1,   2,   3],
       [  4,   5,   6],
       [900, 900, 900]])

Hey! such an intresting output. You noticed buddy! your original array didn't get changed on change of its copy ie. x4.

Still not convinced? Ok lets see if they both share memory or not

In [ ]:
#Check memory share between x1 and x4

memory_x4 = np.shares_memory(x1,x4)
memory_x4

**hstack vs vstack function**


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

NumPy provides a helper function:

1. hstack() to stack along rows.
2. vstack()  to stack along columns

In [ ]:
# stack x1 and x4 along columns.
s1 = np.hstack((x1,x4))
s1


In [ ]:
#stack x1 and x4 along rows
s2 = np.vstack((x1,x4))
s2

We hope now you saw the difference between them.

Fun fact! you can even use concatenate() function to join 2 arrays along with the axis. If axis is not explicitly passed, it is taken as 0 ie. along column

Lets try this function as well

In [ ]:
arr1 = np.array([[1, 2, 4],[5, 8, 9]])
arr2 = np.array([[2, 5, 7],[6, 4, 2]])


##join arr1 and arr2 along rows using concatenate() function
arr4 = np.concatenate((arr1,arr2),axis=0)
arr4



In [ ]:
##join arr1 and arr2 along columns using concatenate() function
arr3 = np.concatenate([arr1,arr2],axis=1)
arr3

## Adding, Insert and delete Numpy array

You can also add 2 arrays using append() function also. This function appends values to end of array

Lets see how

In [ ]:
# append arr2 to arr1
arr5 = np.append(arr1,arr2)
arr5

Lets use insert() function which Inserts values into array before specified index value

In [37]:
# Inserts values into array x1 before index 4 with elements of x4

arr6 = np.insert(x1, 3, x4, axis = 0)
arr6

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [  1,   2,   3],
       [  4,   5,   6],
       [900, 900, 900]])

You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [49]:
# delete 2nd element from array x2

x2_new = np.delete(x2, 1, axis=0)
x2_new

array([[10, 10, 10],
       [ 7,  8,  9]])

Did you see? 2 value is deleted from x2 which was at index position 2

Good Job learner!